[frontend]
vm-web-01-prd ansible_host=52.236.172.130 ansible_user=azureuser ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[backend]
vm-db-01-prd ansible_host=10.0.2.4 ansible_user=azureuser ansible_ssh_common_args='-o ProxyJump=azureuser@52.236.172.130 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'