[frontend]
vm-web-01-prd ansible_host=20.61.201.162 ansible_user=azureuser

[backend]
vm-db-01-prd ansible_host=10.0.2.4 ansible_user=azureuser ansible_ssh_common_args='-o ProxyJump=azureuser@20.61.201.162'
